PERIPHERALS = pit adc pwm
DRIVERS = pacer usb_serial adxl345 panic piezo nrf24 ledtape
SRC = hat.c radio.c led_tape.c buzzer.c mmelody.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
